services:
  perc-users:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: perc-users
    volumes:
      - ./src:/code/src
    ports:
      - 50057:50057
    environment:
      MI_ENV_VARIABLE: "example"
      USER_API_URL: "https://jsonplaceholder.typicode.com/users"
    env_file:
      - .env
    networks:
      - ccp

networks:
  ccp:
    external: true


